name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up .NET
      uses: xt0rted/setup-dotnet@v1.0.0
      with
        dotnet-version: |
          3.1.x
          4.6.x
          6.0.x
    - name: Restore dependencies
      run: dotnet restore src/Nino.sln
    - name: Build
      run: dotnet build src/Nino.sln --no-restore
    - name: Test
      run: dotnet test src/Nino.sln --no-build --verbosity normal
