# This is a basic workflow to help you get started with Actions

name: Dependabot Auto Merge

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  auto-merge:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Dependabot Auto Merge
        # You may pin to the exact commit or the version.
        # uses: ahmadnassri/action-dependabot-auto-merge@c0e574b9d8c2e0e029e8e8d1d44b13ffbfd14f0a
        uses: ahmadnassri/action-dependabot-auto-merge@v2.3.1
        with:
          # The GitHub token used to merge the pull-request
          github-token: ${{ secrets.mytoken }}
